# Generated by Django 3.2.6 on 2021-09-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration'), ('lvl1', 'Lvl1'), ('lvl2', 'Lvl2')], default='registration', max_length=50),
        ),
    ]
